jogo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from jogo.views import cancelar_template, index, \
    partidas, ganhadores, cartela, login_page, logout_page, criarpartida, \
    cartelas, configuracao, cancelar_partida, cancelar_bilhete, partida_edit, \
    partida_automatica, automatos, parar_automato, sortear_template, editar_template, manter_contas_view, \
    aumentar_cartelas, forcar_sorteio, status_jogador, mudar_senha_jogador, pagamento, zerar_creditos, \
    campos_alterar_ativo, campos_alterar_obrigatorio, afiliados, afiliado

from .views import configuracao_visual, jogadores, realtime_data
from .views_api_media import logo_promo, media_login, nome_server, media_logo, media_favicon, media_fundo
from .views_api_online import dados_bilhete, get_politicas_de_privacidade_kol, get_regras_kol, proximos_kol, \
    data_hora_servidor, ultimos_ganhadores_kol, ultimos_bilhetes
from .views_api_tela import resultado_sorteio, proximos, proximos_especiais, historico, status, ultimos_ganhadores
from .views_aplicacao import CadastroJogador, LoginJogador, PegarCartela, ConfiguracaoAplicacaoView, \
    RequisicaoPremioAplicacaoView, AfiliadoView, PegarCartelaBonus, DadosJogadorView
#from .views_social_instagram import index_social, gerar_bilhete

urlpatterns = [
    path('', index),
    path('logout/',logout_page, name='logout'),
    path('login/',login_page),
    path('partidas/', partidas),
    path('criar_partida/', criarpartida),

    path('ganhadores/', ganhadores),
    path('jogadores/', jogadores),
    path('afiliados/', afiliados),
    path('afiliado/<int:afiliado_id>/', afiliado),
    path('cartelas/', cartelas),
    path('configuracao-visual/', configuracao_visual),
    path('configuracao/', configuracao),

    path('cancelar_partida/<int:partida_id>/',cancelar_partida),
    path('cancelar_bilhete/<str:hash>/',cancelar_bilhete),
    path('partida_edit/<int:partida_id>/', partida_edit),

    path("partidas/<int:partida_id>/aumentar/<str:quantidade>/",aumentar_cartelas),
    path("partidas/<int:partida_id>/force/",forcar_sorteio),

    path('realtime_data/',realtime_data),

    path("jogador/<int:jogador_id>/status/<int:status>/", status_jogador),
    path("jogador/<int:jogador_id>/senha/", mudar_senha_jogador),

    path("pagamento/",pagamento),
    path("zerar_creditos/",zerar_creditos),

    path("campo/<int:campo_id>/ativo/",campos_alterar_ativo),
    path("campo/<int:campo_id>/obrigatorio/",campos_alterar_obrigatorio),

    path('api/v1/', include(
        [
            path('sorteio/<int:local_id>/<int:sorteio_id>/', resultado_sorteio),
            path('proximossorteios/', proximos),
            path('proximos_especiais/', proximos_especiais),
            path('historico/', historico),
            path('status/<str:partida_id>/',status),
            path('ultimos_ganhadores/',ultimos_ganhadores),
        ]
    )),

    path('api/kol/', include(
        [
            path('bilhete/<str:hash>/', dados_bilhete,name="dados_bilhete"),
            path('proximossorteios/', proximos_kol),
            path('data_hora/', data_hora_servidor),
            path('ultimos_ganhadores/', ultimos_ganhadores_kol),
            path('ultimos_ganhadores/<int:sorteio_id>/', ultimos_ganhadores_kol),
            path('regras/',get_regras_kol),
            path('politicas_de_privacidade/',get_politicas_de_privacidade_kol),
            path("ultimos_bilhetes/",ultimos_bilhetes),
        ]

    )),

    path('api/media/', include(
        [
            path('logo/', media_logo),
            path('favicon/',media_favicon),
            path('login/',media_login),
            path('nome/',nome_server),
            path('logo_promo/',logo_promo),
            path('fundo/',media_fundo)
        ]
    )),

    path("api/cadastro/", CadastroJogador.as_view(), name="api_cadastro"),
    path("api/login/",LoginJogador.as_view(), name="api_login"),
    path("api/gerar_bilhete/",PegarCartela.as_view(), name="api_gerar_bilhete"),
    path("api/configuracao_aplicacao/", ConfiguracaoAplicacaoView.as_view(), name="api_configuracao_aplicacao"),
    path("api/requisicao_premio_aplicacao/", RequisicaoPremioAplicacaoView.as_view(), name="api_requisicao_premio_aplicacao"),
    path("api/afiliado/",AfiliadoView.as_view(), name="api_afiliado"),
    path("api/gerar_bilhete_bonus/",PegarCartelaBonus.as_view(), name="api_gerar_bilhete_bonus"),
    path("api/dados_jogador/",DadosJogadorView.as_view()),

    path("manter_contas/", manter_contas_view),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
path("api/social/", include(
    [
        path("",index_social),
        path("gerar_bilhete/", gerar_bilhete)
    ]
)),
"""

keno_promo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jogo.urls')),
    path('tinymce/', include('tinymce.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jogo/models.py
import base64
import pickle
import string
import urllib

from django.contrib.postgres.fields import ArrayField
from django.db import models

# Create your models here.
import decimal
import json
import random
import secrets

from datetime import timedelta, datetime, date, time
from django.db.models import Sum, Q

from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

import threading

# Create your models here.
from django.utils.crypto import get_random_string
from django_resized import ResizedImageField

from jogo import local_settings
from jogo.choices import AcaoTipoChoices, AcaoBonus, TipoDebitoBonus
from jogo.constantes import NOME_PESSOAS
from jogo.consts import TipoRedeSocial, LocalBotaoChoices, CampoCadastroChoices
from jogo.websocket_triggers import event_doacoes
from colorfield.fields import ColorField

def configuracao_images_path(instance, filename):
    return 'configuracao/{0}'.format(filename)


def configuracao_biuld_path(instance, filename):
    return 'build/{0}'.format(filename)


class ContadorCartelaPartida(models.Model):
    data = models.DateField(unique=True)
    numeracao = models.IntegerField()

    def __str__(self):
        return f"Dia: {self.data}: {self.numeracao}"

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.id:
            lista = local_settings.INICIO_CONTAGEM_CARTELAS
            self.numeracao = random.choice(lista)
        super().save(force_insert, force_update, using, update_fields)

    def atualizar(self, quantidade):
        self.numeracao += quantidade
        self.save()


class Configuracao(models.Model):
    tempo_min_entre_sorteios = models.PositiveSmallIntegerField(default=1)
    tempo_min_entre_sorteios_E = models.PositiveSmallIntegerField(default=30)
    tempo_min_entre_sorteios_SE = models.PositiveSmallIntegerField(default=30)
    iniciar_sorteio_em = models.PositiveSmallIntegerField(default=15)
    liberar_resultado_sorteio_em = models.PositiveSmallIntegerField(default=5)
    logo_login = models.ImageField(upload_to=configuracao_images_path, blank=True, null=True)
    logo_dash = models.ImageField(upload_to=configuracao_images_path, blank=True, null=True)
    favicon = models.FileField(upload_to=configuracao_images_path, blank=True, null=True)
    logo_promo = models.FileField(upload_to=configuracao_images_path, blank=True, null=True)
    fundo_front = models.FileField(upload_to=configuracao_images_path, blank=True, null=True)
    nome_server = models.CharField(max_length=100, blank=True, null=True)
    token_server = models.CharField(max_length=100, blank=True, null=True)

    # COM VENDAS DE CARTELAS
    edit_data_antecipar = models.BooleanField(default=False)
    edit_data_adiar = models.BooleanField(default=False)
    edit_horario_antecipar = models.BooleanField(default=False)
    edit_horario_adiar = models.BooleanField(default=False)
    edit_nome = models.BooleanField(default=False)
    edit_kuadra = models.BooleanField(default=False)
    edit_kina = models.BooleanField(default=False)
    edit_keno = models.BooleanField(default=False)

    cancelar_bilhete = models.BooleanField(default=False)
    tempo_expirar_template = models.PositiveSmallIntegerField(default=2)

    # PARA WEBGL
    tempo_sorteio_online = models.PositiveSmallIntegerField(default=10)
    imprimir_qrcode = models.BooleanField(default=False)

    # Usar realtime data
    usar_realtime = models.BooleanField(default=False)

    # Automato
    quantidade_cartelas_compradas = models.PositiveIntegerField(default=1000)

    # Modo de pagar premio
    pagamento_automatico = models.BooleanField(default=True)

    # Versao da branch
    versao = models.CharField(max_length=100, blank=True, null=True)

    # instagram compatibilidade
    perfil_default = models.URLField(blank=True, null=True)
    reter_jogadores = models.BooleanField(default=True)

    # regras e politica
    regras = models.TextField(default="")

    politicas_de_privacidade = models.TextField(default="")

    incluir_codigo = models.BooleanField(default=True)
    incluir_sorteio = models.BooleanField(default=True)
    incluir_valor = models.BooleanField(default=True)
    incluir_apelido = models.BooleanField(default=True)

    velocidade_sorteio = models.PositiveIntegerField(default=3000)
    velocidade_sorteio_online = models.PositiveIntegerField(default=3000)

    max_vitorias_jogador = models.PositiveSmallIntegerField(default=0)
    numero_cadastro_libera_jogador = models.PositiveSmallIntegerField(default=1)
    creditos_bonus_gera_bilhete = models.PositiveSmallIntegerField(default=1)
    max_cartelas_bonus_por_sorteio = models.PositiveSmallIntegerField(default=0)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.id:
            self.token_server = secrets.token_hex(20)
        super().save(force_insert, force_update, using, update_fields)

class ConfiguracaoInstagram(models.Model):
    # Conexao com o instagram
    instagram_connection = models.BinaryField(blank=True, null=True)
    perfil_default = models.URLField(blank=True, null=True)
    validacao_ativa = models.BooleanField(default=False)
    publicacao_uma_vez_dia = models.BooleanField(default=True)
    perfil_id = models.CharField(max_length=50, blank=True, null=True)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.id:
            conf = Configuracao.objects.last()
            if conf and conf.instagram_connection:
                conexao = pickle.loads(conf.instagram_connection)
                self.instagram_connection = pickle.dumps(conexao)
        super().save(force_insert,force_update,using,update_fields)


class Usuario(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    cpf = models.CharField(max_length=20, verbose_name="CPF", blank=True, null=True)
    fone = models.CharField(max_length=50)
    email = models.EmailField(blank=True, null=True)
    ativo = models.BooleanField(default=True)
    data_criacao = models.DateTimeField(auto_now_add=True)
    token = models.CharField(max_length=200, unique=True, blank=True)
    sessao_atual = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return f"{str(self.id).zfill(3)} - {self.usuario.first_name.title()}"

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.id:
            self.token = secrets.token_hex(20)
            creating = True

        super().save(force_insert, force_update, using, update_fields)



class Regiao(models.Model):
    nome = models.CharField(max_length=200)
    descricao = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nome

TEMPO_MINIMO_ANTECIPADO = {
    (timedelta(minutes = 30), "30 Min"), (timedelta(minutes = 45), "45 Min"), (timedelta(minutes = 60), "60 Min"),
    (timedelta(minutes = 90), "90 Min"), (timedelta(minutes = 120), "120 Min")
}

TEMPO_CHOICES = (
    (1, "1 Minuto"),(2,'2 Minutos'),(3, "3 Minutos"), (4, "4 Minutos"), (5, "5 Minutos")
)
TEMPO_LIBERAR_CHOICES = (
    (3, "3 Minutos"),(4,"4 Minutos"),(5, "5 Minutos"),(6,'6 Minutos'),(7, "7 Minutos"), (8, "8 Minutos"), (9, "9 Minutos"), (10, "10 Minutos")
)

PARTIDA_TIPOS_CHOICES = (
    (1,"NORMAL"),(2,"ESPECIAL"),(3,"SUPER ESPECIAL")
)

# NOVA CLASSE
class Regra(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

# NOVA CLASSE
class PerfilSocial(models.Model):
    url = models.CharField(max_length=255, unique=True)
    perfil_id = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.url

# NOVA CLASSE
class Acao(models.Model):
    regra = models.ForeignKey(Regra, on_delete=models.PROTECT)
    tipo = models.CharField(max_length=20, choices=AcaoTipoChoices.choices)
    perfil_social = models.ForeignKey(PerfilSocial, on_delete=models.PROTECT)

    def __str__(self):
        return self.get_tipo_display() + " " + str(self.perfil_social)


class Partida(models.Model):
    # NOVO CAMPO
    regra = models.ForeignKey(Regra, on_delete=models.PROTECT)

    valor_kuadra = models.DecimalField(default=20.00, decimal_places=2, max_digits=6)
    valor_kina = models.DecimalField(default=20.00, decimal_places=2, max_digits=6)
    valor_keno = models.DecimalField(default=100.00, decimal_places=2, max_digits=8)
    tipo_rodada = models.PositiveSmallIntegerField(default=1, choices=PARTIDA_TIPOS_CHOICES)
    data_partida = models.DateTimeField()
    data_inicio = models.DateTimeField(blank=True, null=True)
    data_fim = models.DateTimeField(blank=True, null=True)
    data_cadastro = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.PROTECT)
    bolas_sorteadas = models.CharField(max_length=255, null=True, blank=True)

    # NOVO CAMPO
    cartelas_receberam_sorteio = models.ManyToManyField('Cartela', blank=True, related_name="cartelas_receberam_sorteio")

    bola_kuadra = models.PositiveSmallIntegerField(null=True, blank=True)
    bola_kina = models.PositiveSmallIntegerField(null=True, blank=True)
    bola_keno = models.PositiveSmallIntegerField(null=True, blank=True)
    num_cartelas = models.IntegerField(default=0)
    em_sorteio = models.BooleanField(default=False)
    cartelas_participantes = models.TextField(blank=True, null=True)
    sorteio = models.TextField(blank=True, null=True)
    cancelado = models.BooleanField(default=False)
    nome_sorteio = models.CharField(max_length=200, blank=True, null=True)
    partida_automatizada = models.BooleanField(default=False, null=True)
    id_automato = models.BigIntegerField(blank=True, null=True)
    premios_set = models.DecimalField(decimal_places=2, max_digits=10, default=0.00)

jogo/templates/401.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Super Sorte | Painel Administrativo</title>
  <link rel="shortcut icon" href="{% static 'favicon.png' %}"/>
  <link rel="stylesheet" href="/static/error.css">
</head>
<body>
  <div class="container">
    <div class="container-error">
      <h1 class="title">Oops!</h1>
      <h2 class="sub-title">401 - Error</h2>
      <p class="paragrafo">Acesso não autorizado!</p>
      <p class="sub-paragrafo">Por favor, entrar em contato com o suporte.</p>
    </div>
    <div class="container-icon">
      <img class="icon-error" src="/static/Icone_Erro_-_404.svg" alt="">
    </div>
  </div>
</body>
</html>

jogo/templates/configuracao_instagram.html
{% extends "index.html" %}
{% block titulo %}
CONFIGURAÇÃO
{% endblock %}
{% block nav-bar %}


        {% if messages %}
        <div class="row justify-content-center bg-success">
            <div class="row col-lg-12 col-md-12 col-sm-12 justify-content-center padding-zero">
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% endif %}

        <div class="row justify-content-center">
            <div class="row col-lg-12 col-md-12 col-sm-12 justify-content-center padding-zero">
                <div class="col-md-12">
                    <div class="row card card-tabs col-md-12 padding-zero">
                        <div class="col-md-12 padding-zero">
                            <div class="row card col-md-12 container-card justify-content-center container-center">
                                <nav class="col-12 tab">
                                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                                      <button class="nav-link active-tabs tabs-margin" id="jogo-conf" data-bs-toggle="tab" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Configuração Instagram</button>
                                      <button class="nav-link deactivate-tabs tabs-margin" id="server-conf" data-bs-toggle="tab" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Monitoramento das Contas</button>
                                    </div>
                                </nav>
                            </div>
                        </div>
                        
                        <form class="col-12 row justify-content-start form-group" method="post">
                        {% csrf_token %}
                            {% if form.non_fields_errors %}
                            <div class="errors-box container-error container-center">
                              {{ form.non_fields_errors }}
                            </div>
                        {% endif %}
                            {% if form.fields_errors %}
                            <div class="errors-box container-error container-center">
                              {{ form.fields_errors }}
                            </div>
                        {% endif %}
                            <div class="row container-jogo-conf">
                                <div class="col-lg-12 col-md-12 col-sm-12 container-input-create input-container-conf">
                                    <label class="form-label" for="id_perfil_default">Perfil do jogo (padrão)</label>
                                    <div class="form-control-wrap col-sm-12">
                                        {{ configuracao.perfil_default }} - ({{ configuracao.perfil_id }})
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12 container-input-create input-container-conf">
                                    <label class="form-label" for="id_validacao_ativa">Ativar validação pelo instagram?</label>
                                    <div class="form-control-wrap">
                                        {{ form.validacao_ativa }}
                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-6 col-sm-12 container-input-create input-container-conf">
                                    <label class="form-label" for="id_publicacao_uma_vez_dia">Publicação automatica 1 vez por dia (com validação ativa)?</label>
                                    <div class="form-control-wrap">
                                        {{ form.publicacao_uma_vez_dia }}
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 container-input-create input-container-conf">
                                    <label class="form-label" for="id_mensagem_nao_segue">Mensagem para quem nao segue o perfil</label>
                                    <div class="form-control-wrap">
                                        {{ form.mensagem_nao_segue }}
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 container-input-create input-container-conf">
                                    <label class="form-label" for="id_mensagem_nao_existe">Mensagem para perfil não encontrado</label>
                                    <div class="form-control-wrap">
                                        {{ form.mensagem_nao_existe }}
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 container-input-create input-container-conf">
                                    <label class="form-label" for="id_mensagem_nao_ha_sorteios">Mensagem para quando não houver sorteios futuros</label>
                                    <div class="form-control-wrap">
                                        {{ form.mensagem_nao_ha_sorteios }}
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 container-input-create input-container-conf">
                                    <label class="form-label" for="id_mensagem_ja_participa_sorteio">Mensagem para quem já está participando do sorteio atual</label>
                                    <div class="form-control-wrap">
                                        {{ form.mensagem_ja_participa_sorteio }}
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 container-input-create input-container-conf">
                                    <label class="form-label" for="id_mensagem_cartelas_esgotadas">Mensagem para cartelas esgotadas (modo retenção)</label>
                                    <div class="form-control-wrap">
                                        {{ form.mensagem_cartelas_esgotadas }}
                                    </div>
                                </div>
                                    <div class="col-12 justify-content-end text-right container-input-create container-salve-conf">
                                        <div class="form-control-wrap">
                                            <button class="btn btn-success btn-create-secondary">Salvar</button>
                                        </div>
                                    </div>
                            </div>
                            <div class="row container-server-conf">
                                {% for conta in contas %}
                                <div class="row justify-content-center col-lg-12 col-sm-12 container-input-create">
                                    <div class="form-group">
                                        <div class="form-control-wrap">
                                            <h6 class="conf-subtitle">Conta {{ conta.username }} {% if conta.instagram_id %}- {{ conta.instagram_id }}{% endif %}</h6>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-4 container-input-create input-container-conf">
                                    {% if conta.ativo %}
                                    <label class="form-label caixa-texto-verde" for="id_nome_server">Ativo</label>
                                    {% else %}
                                    <label class="form-label caixa-texto-vermelho" for="id_nome_server">Inativo</label>
                                    {% endif %}

                                        {% if conta.ativo %}
                                        <a href="/conta/{{ conta.id }}/status/" class="btn btn-sm btn-gray round">Desativar</a>
                                            {% else %}
                                        <a href="/conta/{{ conta.id }}/status/" class="btn btn-sm btn-gray">Ativar</a>
                                            {% endif %}

                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-4 container-input-create input-container-conf">
                                    <label class="form-label" for="id_nome_server">Atenção</label>
                                    <div class="form-control-wrap">
                                        {{ conta.atencao }}
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-4 container-input-create input-container-conf">
                                    <label class="form-label" for="id_proxy">Proxy</label>
                                    <div class="form-control-wrap">
                                        {% if conta.proxy %}{{ conta.proxy }}{% endif %}
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 container-input-create input-container-conf">
                                    <label class="form-label" for="id_ultimo_acesso">Data último acesso</label>
                                    <div class="form-control-wrap">
                                        {{ conta.ultimo_acesso }}
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 container-input-create input-container-conf">
                                    <label class="form-label" for="id_ultimo_login">Data último login</label>
                                    <div class="form-control-wrap">
                                        {% if conta.ultimo_login %}{{ conta.ultimo_login }}{% endif %}
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 container-input-create input-container-conf">
                                    <label class="form-label" for="id_settings">Settings</label>
                                    <div class="form-control-wrap">
                                        {% if conta.settings %}{{ conta.settings }}{% endif %}
                                    </div>
                                </div>

                                {% endfor %}
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>

<!-- content @e -->
<!------------------------------------------------------------------------------------------------------------>
<script>
    
    const jogo = $('#jogo-conf');
    const server = $('#server-conf');

    const jogoContainer = $('.container-jogo-conf');
    const serverContainer = $('.container-server-conf');

    $(jogo).click(function () {
        jogo.removeClass('deactivate-tabs');
        jogo.addClass('active-tabs');
        jogoContainer.css('display','flex');

        server.removeClass('active-tabs');
        server.addClass('deactivate-tabs');
        serverContainer.css('display','none');
    })

    $(server).click(function () {
        server.removeClass('deactivate-tabs');
        server.addClass('active-tabs');
        serverContainer.css('display','flex');

        jogo.removeClass('active-tabs');
        jogo.addClass('deactivate-tabs');
        jogoContainer.css('display','none');
    })

</script>

{% endblock %}

jogo/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% if titulo %}{{ titulo }}{% else %}Mr Keno{% endif %}</title>
    <link rel="shortcut icon" href="{% if favicon %}{{ favicon.url }}{% else %}
        {% static 'images-logo/favicon.png' %}{% endif %}"/>
    <link rel="stylesheet" href="/static/login.css">

    <style>
        

        .logo-login{
            width: 250px;
        }

    </style>
</head>

    <div class="container-login">
        <form class="form-container-login" action="" method="post">
            {% csrf_token %}
            <div class="container-logo-login">
                <img src="{% if imagem %}{{ imagem.url }}{% else %}
                    /static/images-logo/mr-keno-login.png{% endif %}" class="logo-login"> </div>
            {% if error %}
            <div class="" style="background-color:red;">{{ error }}</div>
            {% endif %}
            <div class="container-input-login">
                <label class="label-login" for="user"><img class="icon-login" src="/static/assets-login/man-user (1).svg" alt=""></label>
                <input class="input-login" type="text" placeholder="usuário" id="user" name="user">
            </div>
            
            <div class="container-input-login">
                <label class="label-login" for="password"><img class="icon-login" src="/static/assets-login/lock (1).svg" alt=""></label>
                <input class="input-login" type="password" placeholder="senha" id="password" name="password">
            </div>

            <div class="container-btn-login">
                <input type="submit" class="btn-login" value="Entrar"/>
            </div>
            <div class="row">
                <div>
                    <p style="color:#027d9c !important;">{% if versao %}Versão: {{ versao }}{% endif %}</p>
                </div>
            </div>
        </form>

    </div>


    
</body>
</html>